GeoRef/Controllers/EstadosController.cs
using GeoRef.Models;
using GeoRef.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace GeoRef.Controllers
{
    public class EstadosController : Controller
    {
        private readonly IEstadosService _estadosService;
        public EstadosController(IEstadosService estadosService)
        {
            _estadosService = estadosService;
        }

        public async Task<IActionResult> EstadoIndex()
        {
            List<EstadosDto> list = new();
            var response = await _estadosService.GetAllEstadosAsync<ResponseDto>();
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<EstadosDto>>(Convert.ToString(response.Result));
            }
            return View(list);
        }
        public async Task<IActionResult> EstadoCreate()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> EstadoCreate(EstadosDto estadosDto)
        {
            if (ModelState.IsValid)
            {
                var response = await _estadosService.CreateEstadoAsync<ResponseDto>(estadosDto);
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(EstadoIndex));
                }
            }
            return View(estadosDto);
        }
        public async Task<IActionResult> EstadoEdit(int idEstado)
        {
            var response = await _estadosService.GetEstadoByIdAsync<ResponseDto>(idEstado);
            if (response != null && response.IsSuccess)
            {
                EstadosDto estados = JsonConvert.DeserializeObject<EstadosDto>(Convert.ToString(response.Result));
                return View(estados);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> EstadoEdit(EstadosDto estadosDto)
        {
            if (ModelState.IsValid)
            {
                var response = await _estadosService.UpdateEstadosAsync<ResponseDto>(estadosDto);
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(EstadoIndex));
                }
            }
            return View(estadosDto);
        }
        public async Task<IActionResult> EstadoDelete(int idEstado)
        {
            var response = await _estadosService.GetEstadoByIdAsync<ResponseDto>(idEstado);
            if (response != null && response.IsSuccess)
            {
                EstadosDto estadosDto = JsonConvert.DeserializeObject<EstadosDto>(Convert.ToString(response.Result));
                return View(estadosDto);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> EstadoDelete(EstadosDto estadosDto)
        {
            if (ModelState.IsValid)
            {
                var response = await _estadosService.DeleteEstadoAsync<ResponseDto>(estadosDto.idEstado);
                if (response.IsSuccess)
                {
                    return RedirectToAction(nameof(EstadoIndex));
                }
            }
            return View(estadosDto);
        }
    }
}

GeoRef/Controllers/GeoReferenceController.cs
using GeoRef.Models;
using GeoRef.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace GeoRef.Controllers
{
    public class GeoReferenceController : Controller
    {
        private readonly IGeoReferencesService _geoReferencesService;
        public GeoReferenceController(IGeoReferencesService geoReferencesService)
        {
            _geoReferencesService = geoReferencesService;
        }

        public async Task<IActionResult> GeoReferenceIndex()
        {
            List<GeoReferenceDto> list = new();
            var response = await _geoReferencesService.GetAllGeoReferenceAsync<ResponseDto>();
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<GeoReferenceDto>>(Convert.ToString(response.Result));
            }
            return View(list);
        }
        public async Task<IActionResult> GeoReferenceCreate()
        {
            var response = await _geoReferencesService.GetEstados<ResponseDto>();
            if (response != null && response.IsSuccess)
            {
                GeoReferenceVM geoReferenceVM = JsonConvert.DeserializeObject<GeoReferenceVM>(Convert.ToString(response.Result));
                ViewBag.EstadosList = geoReferenceVM.TypeDropDown;
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> GeoReferenceCreate(GeoReferenceDto geoReferenceDto)
        {
            ModelState.Remove("Estados");
            if (ModelState.IsValid)
            {
                var response = await _geoReferencesService.CreateGeoReferenceAsync<ResponseDto>(geoReferenceDto);
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(GeoReferenceIndex));
                }
            }
            return View(geoReferenceDto);
        }
        public async Task<IActionResult> GeoReferenceEdit(int idGeoReference)
        {
            var response = await _geoReferencesService.GetGeoReferenceByIdAsync<ResponseDto>(idGeoReference);
            var response2 = await _geoReferencesService.GetEstados<ResponseDto>();
            if (response2 != null && response2.IsSuccess)
            {
                GeoReferenceVM geoReferenceVM = JsonConvert.DeserializeObject<GeoReferenceVM>(Convert.ToString(response2.Result));
                ViewBag.EstadosList = geoReferenceVM.TypeDropDown;
            }
            if (response != null && response.IsSuccess)
            {
                GeoReferenceDto geoReference = JsonConvert.DeserializeObject<GeoReferenceDto>(Convert.ToString(response.Result));
                return View(geoReference);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> GeoReferenceEdit(GeoReferenceDto geoReferenceDto)
        {
            ModelState.Remove("Estados");
            if (ModelState.IsValid)
            {
                var response = await _geoReferencesService.UpdateGeoReferenceAsync<ResponseDto>(geoReferenceDto);
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(GeoReferenceIndex));
                }
            }
            return View(geoReferenceDto);
        }
        public async Task<IActionResult> GeoReferenceDelete(int idGeoReference)
        {
            var response = await _geoReferencesService.GetGeoReferenceByIdAsync<ResponseDto>(idGeoReference);
            var response2 = await _geoReferencesService.GetEstados<ResponseDto>();
            if (response2 != null && response2.IsSuccess)
            {
                GeoReferenceVM geoReferenceVM = JsonConvert.DeserializeObject<GeoReferenceVM>(Convert.ToString(response2.Result));
                ViewBag.EstadosList = geoReferenceVM.TypeDropDown;
            }
            if (response != null && response.IsSuccess)
            {
                GeoReferenceDto geoReference = JsonConvert.DeserializeObject<GeoReferenceDto>(Convert.ToString(response.Result));
                return View(geoReference);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> GeoReferenceDelete(GeoReferenceDto geoReferenceDto)
        {
            if (ModelState.IsValid)
            {
                var response = await _geoReferencesService.DeleteGeoReferenceAsync<ResponseDto>(geoReferenceDto.idGeoreferencia);
                if (response.IsSuccess)
                {
                    return RedirectToAction(nameof(GeoReferenceIndex));
                }
            }
            return View(geoReferenceDto);
        }
    }
}

GeoRef/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GeoRef</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GeoRef.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GeoRef</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial"></partial>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item pt-lg-1">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item pt-lg-1">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estados" asp-action="EstadoIndex">Estados</a>
                        </li>
                        <li class="nav-item pt-lg-1">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GeoReference" asp-action="GeoReferenceIndex">GeoReferencias</a>
                        </li>
                        <li class="nav-item pt-lg-1">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - GeoRef - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>